name: rescado
description: Adopt, don't shop
version: 1.0.0+SNAPSHOT
publish_to: 'none'

environment:
  sdk: ">=2.16.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # flutter gen-l10n
    sdk: flutter

  animations: ^2.0.2
  collection: ^1.15.0
  device_info_plus: ^3.2.0
  dots_indicator: ^2.1.0
  firebase_analytics: ^9.0.5 # Required for Crashlytics on Android, but seems to be a bug currently, seeing issues on GitHub
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_storage: ^10.2.9
  flutter_hooks: ^0.18.1
  flutter_svg: ^1.0.0
  geolocator: ^8.0.1
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  jwt_decoder: ^2.0.1
  logger: ^1.1.0
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: true
  image_path_android: "assets/appicon-android.png"
  ios: true
  image_path_ios: "assets/appicon-ios.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/dummies/
    - assets/icons/
    - assets/illustrations/
    - assets/logo/

  fonts:
   - family: M+ Rounded 1c
     fonts:
       - asset: fonts/MPLUSRounded1c-Thin.ttf
         weight: 100
       - asset: fonts/MPLUSRounded1c-Light.ttf
         weight: 300
       - asset: fonts/MPLUSRounded1c-Regular.ttf
         weight: 400
       - asset: fonts/MPLUSRounded1c-Medium.ttf
         weight: 500
       - asset: fonts/MPLUSRounded1c-Bold.ttf
         weight: 700
       - asset: fonts/MPLUSRounded1c-ExtraBold.ttf
         weight: 800
       - asset: fonts/MPLUSRounded1c-Black.ttf
         weight: 900
