name: Set up environment

runs:
  using: composite
  steps:
    - name: Setup Java 12
      id: setup-java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: 'adopt'
        java-version: '12'
    - name: Setup Flutter 2.10.5
      id: setup-flutter
      uses: subosito/flutter-action@v2.4.0
      with:
        channel: 'stable'
        flutter-version: '2.10.5'
    - name: Fetch dependencies
      id: fetch-dependencies
      run: flutter pub get
      shell: bash
