name: Set up environment

runs:
  using: composite
  steps:
    - name: Setup Java 12
      id: setup-java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: 'adopt'
        java-version: '12'
    - name: Setup Flutter 2.8.1
      id: setup-flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable'
        flutter-version: '2.8.1'
    - name: Fetch dependencies
      id: fetch-dependencies
      run: flutter pub get
      shell: bash
