name: check quality

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 12
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '12'
      - name: Setup Flutter 2.5.2
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
          flutter-version: '2.5.2'
      - name: Checkout codebase
        uses: actions/checkout@v2.3.4
      - name: Fetch dependencies
        run: flutter pub get
      - name: Verify code quality
        run: .github/workflows/check-quality.sh
