name: make release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup Java 12
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '12'
      - name: Setup Flutter 2.5.2
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
          flutter-version: '2.5.2'
      - name: Checkout codebase
        uses: actions/checkout@v2.3.4
      - name: Fetch dependencies
        run: flutter pub get
      - name: Build Android application
        run: flutter build apk --release
      - name: Archive Android application
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Android build (zipped apk file, unsigned)
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Build iOS application
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip app-release.ipa
      - name: Archive iOS application
        uses: actions/upload-artifact@v2.2.4
        with:
          name: iOS build (zipped ipa file, unsigned)
          path: app-release.ipa
